FROM node:alpine

WORKDIR /home/node/chat

COPY --chown=node:node package.json ./    

RUN npm install                         

COPY --chown=node:node . .              

ENV NODE_PORT=54306

EXPOSE ${NODE_PORT}

USER node

CMD ["node", "tvschat.js"]