events {}

http {
  resolver 127.0.0.11 valid=10s;

  upstream webapp {
    server webapp:54306;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://webapp;
    }

    location /ollama/ {
      proxy_pass http://llm:11434;
    }
  }
}
